#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Templates.Default
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using ChameleonForms;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Component.Config;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class DefaultHtmlHelpers : ChameleonForms.Templates.ChameleonFormsHelperPage
    {

#line 10 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndForm() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 10 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                   


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </form>\r\n");


#line 12 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 12 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 14 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginSection(IHtmlString heading, IHtmlString leadingHtml, HtmlAttributes htmlAttributes) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 14 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                   


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <fieldset");


#line 15 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, htmlAttributes);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 16 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <legend>");


#line 18 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</legend>\r\n");


#line 19 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");


#line 22 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, leadingHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 23 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dl>\r\n");


#line 25 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 25 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 27 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginNestedSection(IHtmlString heading, IHtmlString leadingHtml, HtmlAttributes htmlAttributes)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 28 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
 
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <dt>");


#line 31 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");


#line 32 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <dd>\r\n");


#line 34 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                ");


#line 36 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, leadingHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 37 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <dl");


#line 38 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, htmlAttributes);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 39 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 39 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 41 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndSection() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 41 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </dl>\r\n");

WriteLiteralTo(__razor_helper_writer, "    </fieldset>\r\n");


#line 44 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 44 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 46 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndNestedSection() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 46 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                            


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </dl>\r\n");

WriteLiteralTo(__razor_helper_writer, "            </dd>\r\n");


#line 49 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 49 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 51 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 51 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                          
    foreach (var html in fieldConfiguration.PrependedHtml) {

#line default
#line hidden

#line 52 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              WriteTo(__razor_helper_writer, html);


#line default
#line hidden

#line 52 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                 }


#line default
#line hidden
});

#line 53 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 55 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 55 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                         
    foreach (var html in fieldConfiguration.AppendedHtml) {

#line default
#line hidden

#line 56 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                             WriteTo(__razor_helper_writer, html);


#line default
#line hidden

#line 56 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                }


#line default
#line hidden
});

#line 57 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 59 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 59 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                 
    if (fieldConfiguration.Hint != null) {

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "<div");

WriteLiteralTo(__razor_helper_writer, " class=\"hint\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 60 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              WriteTo(__razor_helper_writer, fieldConfiguration.Hint);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>");


#line 60 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                          }


#line default
#line hidden
});

#line 61 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 63 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginFieldInternal(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, IReadonlyFieldConfiguration fieldConfiguration, IFieldMetadata fieldMetadata, IHtmlString requiredDesignator) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 63 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <dt>");


#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, labelHtml);


#line default
#line hidden

#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, new HtmlString(fieldMetadata != null && fieldMetadata.IsRequired ? requiredDesignator.ToHtmlString() : ""));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");

WriteLiteralTo(__razor_helper_writer, "            <dd");


#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, RenderIfNotEmpty(fieldConfiguration.FieldContainerClasses,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden
WriteLiteralTo(__razor_template_writer, " class=\"");


#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                            WriteTo(__razor_template_writer, fieldConfiguration.FieldContainerClasses);


#line default
#line hidden
WriteLiteralTo(__razor_template_writer, "\"");


#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                           })));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, GetPrependedHtml(fieldConfiguration));


#line default
#line hidden

#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                         WriteTo(__razor_helper_writer, elementHtml);


#line default
#line hidden

#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                     WriteTo(__razor_helper_writer, GetAppendedHtml(fieldConfiguration));


#line default
#line hidden

#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                         WriteTo(__razor_helper_writer, GetHint(fieldConfiguration));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                      WriteTo(__razor_helper_writer, validationHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 67 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 67 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 69 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult Field(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, IFieldMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlString requiredDesignator) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 69 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                         


#line default
#line hidden

#line 70 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));


#line default
#line hidden

#line 70 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                  


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            </dd>\r\n");


#line 72 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 72 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 74 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginField(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, IFieldMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlString requiredDesignator)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 75 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
 


#line default
#line hidden

#line 76 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));


#line default
#line hidden

#line 76 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                  


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <dl>\r\n");


#line 78 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 78 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 80 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndField() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 80 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </dl>\r\n");

WriteLiteralTo(__razor_helper_writer, "            </dd>\r\n");


#line 83 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 83 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 85 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult RequiredDesignator() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 85 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " <em");

WriteLiteralTo(__razor_helper_writer, " class=\"required\"");

WriteLiteralTo(__razor_helper_writer, ">*</em>");


#line 86 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                         

#line default
#line hidden
});

#line 86 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 88 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginNavigation() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 88 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                           


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div class=\"form_navigation\">\r\n");


#line 90 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 90 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 92 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndNavigation() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 92 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                         


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </div>\r\n");


#line 94 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 94 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 96 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginMessage(MessageType messageType, IHtmlString heading) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 96 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "      <div class=\"");


#line 97 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, string.Format("{0}{1}", messageType.ToString().ToLower(), "_message"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\">\r\n");


#line 98 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            if (!string.IsNullOrEmpty(heading.ToHtmlString()))
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          <h3>");


#line 100 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</h3>\r\n");


#line 101 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          <div class=\"message\">\r\n");


#line 103 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 103 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 105 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndMessage() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 105 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "      </div>\r\n");


#line 108 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 108 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 110 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult MessageParagraph(IHtmlString paragraph) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 110 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <p>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 112 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, paragraph);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");

WriteLiteralTo(__razor_helper_writer, "    </p>\r\n");


#line 114 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 114 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 116 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult RadioOrCheckboxList(IEnumerable<IHtml> items) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 116 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                       


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <ul>\r\n");


#line 118 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
foreach(var i in items) {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <li>");


#line 119 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, i.ToIHtmlString());


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</li>\r\n");


#line 120 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </ul>\r\n");


#line 122 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 122 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 125 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult RenderIfNotEmpty(string mayBeEmpty, Func<object, IHtmlString> template) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 125 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                 
    if (!string.IsNullOrEmpty(mayBeEmpty)) {

#line default
#line hidden

#line 126 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
              WriteTo(__razor_helper_writer, template(null));


#line default
#line hidden

#line 126 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                           }


#line default
#line hidden
});

#line 127 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
