#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Templates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
    using Component.Config;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
    using Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public class TwitterBootstrapHtmlHelpers : System.Web.WebPages.HelperPage
    {

#line 9 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndForm() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                   


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </form>\r\n");


#line 11 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 11 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 13 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginSection(IHtmlString title, IHtmlString leadingHtml, HtmlAttributes htmlAttributes) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 13 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <fieldset");


#line 14 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, htmlAttributes);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "        <legend>");


#line 15 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</legend>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 16 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, leadingHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 17 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 17 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 19 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginNestedSection(IHtmlString title, IHtmlString leadingHtml, HtmlAttributes htmlAttributes)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 20 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
 


#line default
#line hidden
});

#line 21 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 23 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndSection() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 23 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </fieldset>\r\n");


#line 25 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 25 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 27 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndNestedSection() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 27 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                            


#line default
#line hidden
});

#line 28 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 30 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 30 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                          
    if (fieldConfiguration != null) {
        foreach (var html in fieldConfiguration.PrependedHtml) {

#line default
#line hidden

#line 32 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                  WriteTo(__razor_helper_writer, html);


#line default
#line hidden

#line 32 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                     }
    }


#line default
#line hidden
});

#line 34 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 36 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 36 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                         
    if (fieldConfiguration != null) {
        foreach (var html in fieldConfiguration.AppendedHtml) {

#line default
#line hidden

#line 38 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                 WriteTo(__razor_helper_writer, html);


#line default
#line hidden

#line 38 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                    }
    }


#line default
#line hidden
});

#line 40 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 42 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 42 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                 
    if (fieldConfiguration != null && fieldConfiguration.Hint != null) {

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "<span");

WriteLiteralTo(__razor_helper_writer, " class=\"help-block\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 43 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                   WriteTo(__razor_helper_writer, fieldConfiguration.Hint);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</span>");


#line 43 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                }


#line default
#line hidden
});

#line 44 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 46 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginFieldInternal(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 46 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                     


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <div class=\"form-group\">\r\n");

WriteLiteralTo(__razor_helper_writer, "            ");


#line 48 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, labelHtml);


#line default
#line hidden

#line 48 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, new HtmlString(fieldMetadata != null && fieldMetadata.IsRequired ? " <em class=\"required\">*</em>" : ""));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");

WriteLiteralTo(__razor_helper_writer, "            ");


#line 49 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, GetPrependedHtml(fieldConfiguration));


#line default
#line hidden

#line 49 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                     WriteTo(__razor_helper_writer, elementHtml);


#line default
#line hidden

#line 49 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                 WriteTo(__razor_helper_writer, GetAppendedHtml(fieldConfiguration));


#line default
#line hidden

#line 49 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                     WriteTo(__razor_helper_writer, GetHint(fieldConfiguration));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 49 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                  WriteTo(__razor_helper_writer, validationHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 50 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 50 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 52 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult Field(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 52 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                        


#line default
#line hidden

#line 53 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata));


#line default
#line hidden

#line 53 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                              


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            </div>\r\n");


#line 55 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 55 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 57 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginField(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 58 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
 


#line default
#line hidden

#line 59 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata));


#line default
#line hidden

#line 59 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                              


#line default
#line hidden
});

#line 60 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 62 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndField() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 62 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            </div>\r\n");


#line 64 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 64 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 66 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginMessage(TwitterAlertType messageType, IHtmlString heading) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 66 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                                                                         


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "      <div class=\"alert ");


#line 67 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, string.Format("alert-{0}", messageType.ToString().ToLower()));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\">\r\n");


#line 68 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
            if (!string.IsNullOrEmpty(heading.ToHtmlString()))
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          <p><strong>");


#line 70 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</strong></p>\r\n");


#line 71 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
            }


#line default
#line hidden
});

#line 72 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 74 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndMessage() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 74 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "      </div>\r\n");


#line 76 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 76 "..\..\Templates\TwitterBootstrapHtmlHelpers.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
