#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Generated
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using Microsoft.AspNetCore.Mvc.Razor;

    #line 4 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Component.Config;
    using ChameleonForms.Templates;

#line default
#line hidden

#line 5 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Enums;
    
    #line default
    #line hidden
    
    #line 2 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.ModelBinding;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class DefaultHtmlHelpers
    {

public static Microsoft.AspNetCore.Mvc.Razor.HelperResult EndForm() {
return new HelperResult(async __razor_helper_writer => {



#line 9 "..\..\DefaultHtmlHelpers.cshtml"
                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </form>\r\n");



#line 11 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult BeginSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes) {
return new HelperResult(async __razor_helper_writer => {



#line 13 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <fieldset");



#line 14 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 15 "..\..\DefaultHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <legend>");



#line 17 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</legend>\r\n");



#line 18 "..\..\DefaultHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 21 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 22 "..\..\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <dl>\r\n");



#line 24 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult BeginNestedSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes)
{
return new HelperResult(async __razor_helper_writer => {



#line 27 "..\..\DefaultHtmlHelpers.cshtml"
 
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dt>");



#line 30 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



#line 31 "..\..\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dd>\r\n");



#line 33 "..\..\DefaultHtmlHelpers.cshtml"
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");



#line 35 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 36 "..\..\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <dl");



#line 37 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 38 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult EndSection() {
return new HelperResult(async __razor_helper_writer => {



#line 40 "..\..\DefaultHtmlHelpers.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </fieldset>\r\n");



#line 43 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult EndNestedSection() {
return new HelperResult(async __razor_helper_writer => {



#line 45 "..\..\DefaultHtmlHelpers.cshtml"
                            

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 48 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
return new HelperResult(async __razor_helper_writer => {



#line 50 "..\..\DefaultHtmlHelpers.cshtml"
                                                                          
    foreach (var html in fieldConfiguration.PrependedHtml) {
#line default
#line hidden


#line 51 "..\..\DefaultHtmlHelpers.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 51 "..\..\DefaultHtmlHelpers.cshtml"
                                                                 }

#line default
#line hidden

});

}


public static HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
return new HelperResult(async __razor_helper_writer => {



#line 54 "..\..\DefaultHtmlHelpers.cshtml"
                                                                         
    foreach (var html in fieldConfiguration.AppendedHtml) {
#line default
#line hidden


#line 55 "..\..\DefaultHtmlHelpers.cshtml"
                WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 55 "..\..\DefaultHtmlHelpers.cshtml"
                                                                }

#line default
#line hidden

});

}


public static HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
return new HelperResult(async __razor_helper_writer => {



#line 58 "..\..\DefaultHtmlHelpers.cshtml"
                                                                 
    if (fieldConfiguration.Hint != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"hint\">");



#line 59 "..\..\DefaultHtmlHelpers.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, fieldConfiguration.Hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 59 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                          }

#line default
#line hidden

});

}


public static HelperResult BeginFieldInternal(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 62 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dt>");



#line 63 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, labelHtml);

#line default
#line hidden



#line 63 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, fieldMetadata != null && fieldMetadata.IsRequired ? requiredDesignator : new HtmlString(""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dd");



#line 64 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, RenderIfNotEmpty(fieldConfiguration.FieldContainerClasses,item => new HelperResult(async __razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " class=\"");



#line 64 "..\..\DefaultHtmlHelpers.cshtml"
                                               WebViewPage.WriteTo(@__razor_template_writer, fieldConfiguration.FieldContainerClasses);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\"");



#line 64 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                                           })));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetPrependedHtml(fieldConfiguration));

#line default
#line hidden



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, elementHtml);

#line default
#line hidden



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, GetAppendedHtml(fieldConfiguration));

#line default
#line hidden



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
                                                            WebViewPage.WriteTo(@__razor_helper_writer, GetHint(fieldConfiguration));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, validationHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 66 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult Field(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 68 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                            

#line default
#line hidden


#line 69 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));

#line default
#line hidden


#line 69 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 71 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult BeginField(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlContent requiredDesignator)
{
return new HelperResult(async __razor_helper_writer => {



#line 74 "..\..\DefaultHtmlHelpers.cshtml"
 

#line default
#line hidden


#line 75 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));

#line default
#line hidden


#line 75 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <dl>\r\n");



#line 77 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult EndField() {
return new HelperResult(async __razor_helper_writer => {



#line 79 "..\..\DefaultHtmlHelpers.cshtml"
                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 82 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult RequiredDesignator() {
return new HelperResult(async __razor_helper_writer => {



#line 84 "..\..\DefaultHtmlHelpers.cshtml"
                              

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <em class=\"required\">*</em>");



#line 85 "..\..\DefaultHtmlHelpers.cshtml"
                                         
#line default
#line hidden

});

                                         }


public static HelperResult BeginNavigation() {
return new HelperResult(async __razor_helper_writer => {



#line 87 "..\..\DefaultHtmlHelpers.cshtml"
                           

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form_navigation\">\r\n");



#line 89 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult EndNavigation() {
return new HelperResult(async __razor_helper_writer => {



#line 91 "..\..\DefaultHtmlHelpers.cshtml"
                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



#line 93 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult BeginMessage(MessageType messageType, IHtmlContent heading, bool emptyHeading) {
return new HelperResult(async __razor_helper_writer => {



#line 95 "..\..\DefaultHtmlHelpers.cshtml"
                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      <div class=\"");



#line 96 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("{0}{1}", messageType.ToString().ToLower(), "_message"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 97 "..\..\DefaultHtmlHelpers.cshtml"
            if (!emptyHeading)
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <h3>");



#line 99 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h3>\r\n");



#line 100 "..\..\DefaultHtmlHelpers.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"message\">\r\n");



#line 102 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult EndMessage() {
return new HelperResult(async __razor_helper_writer => {



#line 104 "..\..\DefaultHtmlHelpers.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      </div>\r\n");



#line 107 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult MessageParagraph(IHtmlContent paragraph) {
return new HelperResult(async __razor_helper_writer => {



#line 109 "..\..\DefaultHtmlHelpers.cshtml"
                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 111 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, paragraph);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </p>\r\n");



#line 113 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult RadioOrCheckboxList(IEnumerable<IHtmlContent> items) {
return new HelperResult(async __razor_helper_writer => {



#line 115 "..\..\DefaultHtmlHelpers.cshtml"
                                                              

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul>\r\n");



#line 117 "..\..\DefaultHtmlHelpers.cshtml"
foreach(var i in items) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li>");



#line 118 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 119 "..\..\DefaultHtmlHelpers.cshtml"
}

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



#line 121 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult RenderIfNotEmpty(string mayBeEmpty, Func<object, IHtmlContent> template) {
return new HelperResult(async __razor_helper_writer => {



#line 124 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                  
    if (!string.IsNullOrEmpty(mayBeEmpty)) {
#line default
#line hidden


#line 125 "..\..\DefaultHtmlHelpers.cshtml"
 WebViewPage.WriteTo(@__razor_helper_writer, template(null));

#line default
#line hidden


#line 125 "..\..\DefaultHtmlHelpers.cshtml"
                                                           }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
