#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Templates.Default
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using Component.Config;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class DefaultHtmlHelpers
    {

public static System.Web.WebPages.HelperResult EndForm() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 8 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </form>\r\n");



#line 10 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginSection(IHtmlString heading, IHtmlString leadingHtml, HtmlAttributes htmlAttributes) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 12 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <fieldset");



#line 13 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 14 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <legend>");



#line 16 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</legend>\r\n");



#line 17 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 20 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 21 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <dl>\r\n");



#line 23 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginNestedSection(IHtmlString heading, IHtmlString leadingHtml, HtmlAttributes htmlAttributes)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 26 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
 
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dt>");



#line 29 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



#line 30 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dd>\r\n");



#line 32 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");



#line 34 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 35 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <dl");



#line 36 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 37 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndSection() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 39 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </fieldset>\r\n");



#line 42 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndNestedSection() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 44 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                            

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 47 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 49 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                          
    foreach (var html in fieldConfiguration.PrependedHtml) {
#line default
#line hidden


#line 50 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 50 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                 }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 53 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                         
    foreach (var html in fieldConfiguration.AppendedHtml) {
#line default
#line hidden


#line 54 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 54 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 57 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                 
    if (fieldConfiguration.Hint != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"hint\">");



#line 58 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, fieldConfiguration.Hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 58 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                          }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginFieldInternal(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata, IHtmlString requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 61 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dt>");



#line 62 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, labelHtml);

#line default
#line hidden



#line 62 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(fieldMetadata != null && fieldMetadata.IsRequired ? requiredDesignator.ToHtmlString() : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dd");



#line 63 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.IsNullOrEmpty(fieldConfiguration.FieldContainerClasses) ? new HtmlString(string.Empty) : new HtmlString(" class=\"" + fieldConfiguration.FieldContainerClasses + "\""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");



#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetPrependedHtml(fieldConfiguration));

#line default
#line hidden



#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, elementHtml);

#line default
#line hidden



#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, GetAppendedHtml(fieldConfiguration));

#line default
#line hidden



#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                            WebViewPage.WriteTo(@__razor_helper_writer, GetHint(fieldConfiguration));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 64 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, validationHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Field(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlString requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 67 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                        

#line default
#line hidden


#line 68 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));

#line default
#line hidden


#line 68 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 70 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginField(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlString requiredDesignator)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 73 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
 

#line default
#line hidden


#line 74 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));

#line default
#line hidden


#line 74 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <dl>\r\n");



#line 76 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndField() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 78 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 81 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RequiredDesignator() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 83 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <em class=\"required\">*</em>");



#line 84 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                         
#line default
#line hidden

});

                                         }


public static System.Web.WebPages.HelperResult BeginNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 86 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                           

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form_navigation\">\r\n");



#line 88 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 90 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



#line 92 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginMessage(MessageType messageType, IHtmlString heading) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 94 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      <div class=\"");



#line 95 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("{0}{1}", messageType.ToString().ToLower(), "_message"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 96 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            if (!string.IsNullOrEmpty(heading.ToHtmlString()))
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <h3>");



#line 98 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h3>\r\n");



#line 99 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"message\">\r\n");



#line 101 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndMessage() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 103 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      </div>\r\n");



#line 106 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult MessageParagraph(IHtmlString paragraph) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 108 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 110 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, paragraph);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </p>\r\n");



#line 112 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RadioOrCheckboxList(IEnumerable<IHtmlString> items) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 114 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                             

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul>\r\n");



#line 116 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
foreach(var i in items) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li>");



#line 117 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 118 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



#line 120 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
