#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Templates.Default
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using Component.Config;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    using Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    public class DefaultHtmlHelpers : System.Web.WebPages.HelperPage
    {

#line 9 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndForm() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 9 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                   


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </form>\r\n");


#line 11 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 11 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 13 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginSection(IHtmlString heading, IHtmlString leadingHtml, HtmlAttributes htmlAttributes) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 13 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                   


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <fieldset");


#line 14 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, htmlAttributes);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 15 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <legend>");


#line 17 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</legend>\r\n");


#line 18 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");


#line 21 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, leadingHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 22 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <dl>\r\n");


#line 24 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 24 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 26 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginNestedSection(IHtmlString heading, IHtmlString leadingHtml, HtmlAttributes htmlAttributes)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 27 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
 
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <dt>");


#line 30 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");


#line 31 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <dd>\r\n");


#line 33 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                ");


#line 35 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, leadingHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 36 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <dl");


#line 37 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, htmlAttributes);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\r\n");


#line 38 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 38 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 40 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndSection() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 40 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </dl>\r\n");

WriteLiteralTo(__razor_helper_writer, "    </fieldset>\r\n");


#line 43 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 43 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 45 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndNestedSection() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 45 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                            


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </dl>\r\n");

WriteLiteralTo(__razor_helper_writer, "            </dd>\r\n");


#line 48 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 48 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 50 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 50 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                          
    foreach (var html in fieldConfiguration.PrependedHtml) {

#line default
#line hidden

#line 51 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              WriteTo(__razor_helper_writer, html);


#line default
#line hidden

#line 51 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                 }


#line default
#line hidden
});

#line 52 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 54 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 54 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                         
    foreach (var html in fieldConfiguration.AppendedHtml) {

#line default
#line hidden

#line 55 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                             WriteTo(__razor_helper_writer, html);


#line default
#line hidden

#line 55 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                }


#line default
#line hidden
});

#line 56 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 58 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 58 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                 
    if (fieldConfiguration.Hint != null) {

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "<div");

WriteLiteralTo(__razor_helper_writer, " class=\"hint\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 59 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              WriteTo(__razor_helper_writer, fieldConfiguration.Hint);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>");


#line 59 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                          }


#line default
#line hidden
});

#line 60 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 62 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginFieldInternal(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata, IHtmlString requiredDesignator) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 62 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                                     


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <dt>");


#line 63 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, labelHtml);


#line default
#line hidden

#line 63 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, new HtmlString(fieldMetadata != null && fieldMetadata.IsRequired ? requiredDesignator.ToHtmlString() : ""));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</dt>\r\n");

WriteLiteralTo(__razor_helper_writer, "            <dd>\r\n");

WriteLiteralTo(__razor_helper_writer, "                ");


#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, GetPrependedHtml(fieldConfiguration));


#line default
#line hidden

#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                         WriteTo(__razor_helper_writer, elementHtml);


#line default
#line hidden

#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                     WriteTo(__razor_helper_writer, GetAppendedHtml(fieldConfiguration));


#line default
#line hidden

#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                         WriteTo(__razor_helper_writer, GetHint(fieldConfiguration));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");


#line 65 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                      WriteTo(__razor_helper_writer, validationHtml);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 66 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 68 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult Field(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlString requiredDesignator) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 68 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                        


#line default
#line hidden

#line 69 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));


#line default
#line hidden

#line 69 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                  


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            </dd>\r\n");


#line 71 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 71 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 73 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginField(IHtmlString labelHtml, IHtmlString elementHtml, IHtmlString validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlString requiredDesignator)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 74 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
 


#line default
#line hidden

#line 75 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));


#line default
#line hidden

#line 75 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                                                                  


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                <dl>\r\n");


#line 77 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 77 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 79 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndField() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 79 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </dl>\r\n");

WriteLiteralTo(__razor_helper_writer, "            </dd>\r\n");


#line 82 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 82 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 84 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult RequiredDesignator() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 84 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                              


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " <em");

WriteLiteralTo(__razor_helper_writer, " class=\"required\"");

WriteLiteralTo(__razor_helper_writer, ">*</em>");


#line 85 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                         

#line default
#line hidden
});

#line 85 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 87 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginNavigation() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 87 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                           


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <div class=\"form_navigation\">\r\n");


#line 89 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 89 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 91 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndNavigation() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 91 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                         


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </div>\r\n");


#line 93 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 93 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 95 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult BeginMessage(MessageType messageType, IHtmlString heading) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 95 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                                    


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "      <div class=\"");


#line 96 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, string.Format("{0}{1}", messageType.ToString().ToLower(), "_message"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\">\r\n");


#line 97 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            if (!string.IsNullOrEmpty(heading.ToHtmlString()))
            {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          <h3>");


#line 99 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, heading);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</h3>\r\n");


#line 100 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
            }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          <div class=\"message\">\r\n");


#line 102 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 102 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 104 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult EndMessage() {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 104 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                      


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "      </div>\r\n");


#line 107 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 107 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 109 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult MessageParagraph(IHtmlString paragraph) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 109 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <p>\r\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 111 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, paragraph);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");

WriteLiteralTo(__razor_helper_writer, "    </p>\r\n");


#line 113 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 113 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

#line 115 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
public static System.Web.WebPages.HelperResult RadioOrCheckboxList(IEnumerable<IHtmlString> items) {
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 115 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
                                                             


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <ul>\r\n");


#line 117 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
foreach(var i in items) {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <li>");


#line 118 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
WriteTo(__razor_helper_writer, i);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</li>\r\n");


#line 119 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </ul>\r\n");


#line 121 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"


#line default
#line hidden
});

#line 121 "..\..\Templates\Default\DefaultHtmlHelpers.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
