#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms;
    
    #line default
    #line hidden
    
    #line 5 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Component.Config;
    
    #line default
    #line hidden
    
    #line 6 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Enums;
    
    #line default
    #line hidden
    
    #line 8 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Templates;
    
    #line default
    #line hidden
    
    #line 3 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.Diagnostics;
    
    #line default
    #line hidden
    
    #line 4 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.ModelBinding;
    
    #line default
    #line hidden
    
    #line 7 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.Razor;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class _DefaultHtmlHelpers_cshtml
    {
        
        #line 12 "..\..\DefaultHtmlHelpers.cshtml"

void EndForm()
{

        #line default
        #line hidden
item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

        #line 16 "..\..\DefaultHtmlHelpers.cshtml"
})    
        #line default
        #line hidden

        #line 16 "..\..\DefaultHtmlHelpers.cshtml"

}


        #line default
        #line hidden

    }
}
#pragma warning restore 1591
