#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Generated
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Component.Config;
    
    #line default
    #line hidden
    
    #line 5 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Enums;
    
    #line default
    #line hidden
    
    #line 7 "..\..\DefaultHtmlHelpers.cshtml"
    using ChameleonForms.Templates;
    
    #line default
    #line hidden
    
    #line 2 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.ModelBinding;
    
    #line default
    #line hidden
    
    #line 6 "..\..\DefaultHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.Razor;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class DefaultHtmlHelpers
    {

public static System.Web.WebPages.HelperResult EndForm() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 11 "..\..\DefaultHtmlHelpers.cshtml"
                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </form>\r\n");



#line 13 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 15 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <fieldset");



#line 16 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 17 "..\..\DefaultHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <legend>");



#line 19 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</legend>\r\n");



#line 20 "..\..\DefaultHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 23 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 24 "..\..\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <dl>\r\n");



#line 26 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginNestedSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 29 "..\..\DefaultHtmlHelpers.cshtml"
 
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dt>");



#line 32 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



#line 33 "..\..\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dd>\r\n");



#line 35 "..\..\DefaultHtmlHelpers.cshtml"
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");



#line 37 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 38 "..\..\DefaultHtmlHelpers.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <dl");



#line 39 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 40 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndSection() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 42 "..\..\DefaultHtmlHelpers.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </fieldset>\r\n");



#line 45 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndNestedSection() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 47 "..\..\DefaultHtmlHelpers.cshtml"
                            

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 50 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 52 "..\..\DefaultHtmlHelpers.cshtml"
                                                                          
    foreach (var html in fieldConfiguration.PrependedHtml) {
#line default
#line hidden


#line 53 "..\..\DefaultHtmlHelpers.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 53 "..\..\DefaultHtmlHelpers.cshtml"
                                                                 }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 56 "..\..\DefaultHtmlHelpers.cshtml"
                                                                         
    foreach (var html in fieldConfiguration.AppendedHtml) {
#line default
#line hidden


#line 57 "..\..\DefaultHtmlHelpers.cshtml"
                WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 57 "..\..\DefaultHtmlHelpers.cshtml"
                                                                }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 60 "..\..\DefaultHtmlHelpers.cshtml"
                                                                 
    if (fieldConfiguration.Hint != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"hint\">");



#line 61 "..\..\DefaultHtmlHelpers.cshtml"
                 WebViewPage.WriteTo(@__razor_helper_writer, fieldConfiguration.Hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 61 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                          }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginFieldInternal(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 64 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dt>");



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, labelHtml);

#line default
#line hidden



#line 65 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(fieldMetadata != null && fieldMetadata.IsRequired ? requiredDesignator.ToHtmlString() : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <dd");



#line 66 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, RenderIfNotEmpty(fieldConfiguration.FieldContainerClasses,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " class=\"");



#line 66 "..\..\DefaultHtmlHelpers.cshtml"
                                               WebViewPage.WriteTo(@__razor_template_writer, fieldConfiguration.FieldContainerClasses);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_template_writer, "\"");



#line 66 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                                           })));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");



#line 67 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetPrependedHtml(fieldConfiguration));

#line default
#line hidden



#line 67 "..\..\DefaultHtmlHelpers.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, elementHtml);

#line default
#line hidden



#line 67 "..\..\DefaultHtmlHelpers.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, GetAppendedHtml(fieldConfiguration));

#line default
#line hidden



#line 67 "..\..\DefaultHtmlHelpers.cshtml"
                                                            WebViewPage.WriteTo(@__razor_helper_writer, GetHint(fieldConfiguration));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 67 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, validationHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 68 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Field(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 70 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                                                                                                            

#line default
#line hidden


#line 71 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));

#line default
#line hidden


#line 71 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 73 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginField(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, IHtmlContent requiredDesignator)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 76 "..\..\DefaultHtmlHelpers.cshtml"
 

#line default
#line hidden


#line 77 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, requiredDesignator));

#line default
#line hidden


#line 77 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <dl>\r\n");



#line 79 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndField() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 81 "..\..\DefaultHtmlHelpers.cshtml"
                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </dl>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </dd>\r\n");



#line 84 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RequiredDesignator() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 86 "..\..\DefaultHtmlHelpers.cshtml"
                              

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <em class=\"required\">*</em>");



#line 87 "..\..\DefaultHtmlHelpers.cshtml"
                                         
#line default
#line hidden

});

                                         }


public static System.Web.WebPages.HelperResult BeginNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 89 "..\..\DefaultHtmlHelpers.cshtml"
                           

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form_navigation\">\r\n");



#line 91 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 93 "..\..\DefaultHtmlHelpers.cshtml"
                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



#line 95 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginMessage(MessageType messageType, IHtmlContent heading) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 97 "..\..\DefaultHtmlHelpers.cshtml"
                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      <div class=\"");



#line 98 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, string.Format("{0}{1}", messageType.ToString().ToLower(), "_message"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 99 "..\..\DefaultHtmlHelpers.cshtml"
            if (!string.IsNullOrEmpty(heading.ToHtmlString()))
            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <h3>");



#line 101 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h3>\r\n");



#line 102 "..\..\DefaultHtmlHelpers.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"message\">\r\n");



#line 104 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndMessage() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 106 "..\..\DefaultHtmlHelpers.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      </div>\r\n");



#line 109 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult MessageParagraph(IHtmlContent paragraph) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 111 "..\..\DefaultHtmlHelpers.cshtml"
                                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <p>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 113 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, paragraph);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </p>\r\n");



#line 115 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RadioOrCheckboxList(IEnumerable<IHtmlContent> items) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 117 "..\..\DefaultHtmlHelpers.cshtml"
                                                              

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul>\r\n");



#line 119 "..\..\DefaultHtmlHelpers.cshtml"
foreach(var i in items) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li>");



#line 120 "..\..\DefaultHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, i);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 121 "..\..\DefaultHtmlHelpers.cshtml"
}

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



#line 123 "..\..\DefaultHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderIfNotEmpty(string mayBeEmpty, Func<object, IHtmlContent> template) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 126 "..\..\DefaultHtmlHelpers.cshtml"
                                                                                  
    if (!string.IsNullOrEmpty(mayBeEmpty)) {
#line default
#line hidden


#line 127 "..\..\DefaultHtmlHelpers.cshtml"
 WebViewPage.WriteTo(@__razor_helper_writer, template(null));

#line default
#line hidden


#line 127 "..\..\DefaultHtmlHelpers.cshtml"
                                                           }

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
