#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Example.Forms
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public static class HtmlHelpers
    {

public static System.Web.WebPages.HelperResult StartForm() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 3 "..\..\Forms\HtmlHelpers.cshtml"
                     

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndForm() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 6 "..\..\Forms\HtmlHelpers.cshtml"
                   

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
